package DBRun.Tokenizer;


// TODO ----- CHANGE ORDER?????
public enum TokenEnum {
    SEMICOLON,USE,CREATE,DATABASE,OR,TABLE,DROP,ALTER,INSERT,INTO,VALUES,SELECT,FROM,WHERE,
    UPDATE,SET,DELETE,JOIN,AND,ON,ADD,TRUE,FALSE,COMMA,STAR,LEFTPARENTHESIS,
    RIGHTPARENTHESIS,OPERATIVE,NUMERATOR, CHARACTER,EQUALS,STRINGLITERAL
}
